#!/bin/bash
# Handoff Script — Continuar sessão Epic 1 Retro (2026-09-20)
# Executar: bash handoff.sh

set -e

PROJECT_ROOT="/Users/thiagoferreira/Documents/FIAP/Fase 5"
cd "$PROJECT_ROOT"

echo "🔄 Handoff — Epic 1 Retrospectiva (2026-09-20)"
echo "=================================================="
echo ""

# Status atual
echo "📊 Estado Atual:"
git status --short
echo ""

# Branches disponíveis
echo "🌳 Branches:"
git branch -v | grep -E "develop|epic|docs"
echo ""

# Commits recentes
echo "📝 Últimos Commits:"
git log --oneline -5
echo ""

echo "🎯 Próximos Passos:"
echo ""
echo "1. REVISAR A RETRO (leitura):"
echo "   cat _bmad-output/implementation-artifacts/epic-1-retro-2026-09-20.md"
echo ""
echo "2. REVISAR O HANDOFF (leitura):"
echo "   cat HANDOFF-SESSION-2026-09-20.md"
echo ""
echo "3. COMEÇAR STORY 1.6 (hotfix transacional):"
echo ""
echo "   a) Criar branch:"
echo "      git checkout -b feature/1-6-fix-transacional"
echo ""
echo "   b) Arquivos a modificar:"
echo "      - agendamento-confirmacao-service/src/main/java/com/filajusta/agendamento/application/command/"
echo "        ExpirarJanelaDeConfirmacao.java"
echo "        AbrirJanelaDeConfirmacao.java"
echo ""
echo "   c) 3 Fixes Necessários:"
echo ""
echo "      FIX 1: @Transactional em método privado"
echo "      • ExpirarJanelaDeConfirmacao.java:99 — mover @Transactional para expirarJanelas()"
echo "      • AbrirJanelaDeConfirmacao.java:82 — idem"
echo ""
echo "      FIX 2: Rollback de batch incorreto"
echo "      • Add PROPAGATION_REQUIRES_NEW em processar()"
echo "      • Cada item = transação independente"
echo ""
echo "      FIX 3: Null checks silenciosos"
echo "      • ExpirarJanelaDeConfirmacao.java:102-121"
echo "      • Throw exception em vez de silent return"
echo ""
echo "   d) Testes novos:"
echo "      • ExpirarJanelaDeConfirmacaoTransactionRollbackTest"
echo "      • AbrirJanelaDeConfirmacaoBatchPartialFailureTest"
echo ""
echo "   e) Build & test:"
echo "      cd agendamento-confirmacao-service"
echo "      mvn clean test"
echo ""
echo "   f) Code review (em contexto isolado):"
echo "      Usar skill: /code-review"
echo ""
echo "   g) Commit & PR:"
echo "      git add ."
echo "      git commit -m 'fix(epic-1-6): resolver 3 achados críticos transacionais'"
echo "      git push -u origin feature/1-6-fix-transacional"
echo "      gh pr create --base develop"
echo ""
echo "4. DEPOIS DE MERGE (Story 1.6):"
echo "   Então: Story 2.1 (Catálogo + Fila FIFO)"
echo ""
echo ""
echo "📚 Referências:"
echo "  - Retro completa: _bmad-output/implementation-artifacts/epic-1-retro-2026-09-20.md"
echo "  - Handoff: HANDOFF-SESSION-2026-09-20.md"
echo "  - PR #54: https://github.com/thiagohaf/adjt-fase5-fila-justa/pull/54"
echo ""
echo "✅ Pronto para continuar!"
